language: node_js

node_js:
  - "9"
  - "8"
  - "6"
  - "4"

services:
  - docker

before_script:
  - docker-compose up -d
  - sleep 60
  - docker-compose ps

script:
  - npm test

after_script:
  - docker-compose down

notifications:
  email:
    on_success: never
    on_failure: always
